services:
  postgresql:
    container_name: postgres_server_se_project
    image: postgres
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: postgres_db
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5433:5432"
    restart: unless-stopped

  minio:
    container_name: minio_server_se_project
    image: minio/minio
    environment:
      MINIO_ROOT_USER: minio_root_user
      MINIO_ROOT_PASSWORD: minio_root_password
    volumes:
      - minio:/data/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data/minio --console-address ":9001"
    restart: unless-stopped

  maildev:
    container_name: maildev_server_se_project
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
    restart: unless-stopped

volumes:
  postgres:
  minio: