server:
  port: 8080

spring:
  data:
    web:
      pageable:
        default-page-size: 10
  servlet:
    multipart:
      max-file-size: 5MB
      enabled: true
      max-request-size: -1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  datasource:
    username: postgres_user
    password: postgres_password
    url: jdbc:postgresql://localhost:5432/postgres_db
  application:
    name: Allora
  mail:
    host: localhost
    port: 1025
    username: mail_username
    password: mail_password
    from: noreply@allora.com
    properties:
      mail:
        smtp:
          trust: "*"
          auth: true
          starttls:
            enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
    test-connection: true

minio:
  url: http://localhost:9000
  access-key: access-key
  secret-key: secret-key
  bucket-name: images

frontend:
  url: http://localhost:3000

jwt:
  duration: 604800000 #7 days
  secret:
    key: 8a6808baa0145ff9d994242f0d11b78b58c54e0c38b883e52284e84da440549c

stripe:
  webhook:
    secret: ${DEVELOPMENT_STRIPE_WEBHOOK_SECRET}
  api:
    key: ${DEVELOPMENT_STRIPE_API_KEY}

recaptcha:
  secret-key: ${DEVELOPMENT_RECAPTCHA_SECRET_KEY}
  verify-url: https://www.google.com/recaptcha/api/siteverify

ai:
  secret-key: ${DEVELOPMENT_AI_SECRET_KEY}
  api-url: https://api.openai.com/v1/chat/completions
