server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 5MB
      enabled: true
      max-request-size: -1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  datasource:
    username: postgres_user
    password: postgres_password
    url: jdbc:postgresql://localhost:5433/postgres_db
  application:
    name: uni-crush
  mail:
    host: localhost
    port: 1025
    username: mail_username
    password: mail_password
    from: contact
    properties:
      mail:
        smtp:
          trust: "*"
          auth: true
          starttls:
            enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
    test-connection: true